SRC_PLANTUML = $(realpath ./schemas)

BUILD_FOLDER = .temp
DEPEND_PLANTUML = $(BUILD_FOLDER)/.dependPlantUML
OUTPUT_PLANTUML = $(SRC_PLANTUML)
SRC_FILES := $(wildcard $(SRC_PLANTUML)/*.plantuml) $(wildcard $(SRC_PLANTUML)/**/*.plantuml)

all: latex

eps : $(DEPEND_PLANTUML)
	@printf "================================================================================\n"
	@printf "                               Start to generate EPS file\n"
	@printf "================================================================================\n"
	@$(MAKE) $(patsubst $(SRC)/%.plantuml,$(OUTPUT)/%.$@,$(shell ls -1t $(SRC_FILES)))

$(OUTPUT)/%.eps: $(SRC)/%.plantuml
	plantuml -charset UTF-8 -teps -stdrpt:1 -recursive $< -o $(OUTPUT)

png : $(DEPEND_PLANTUML)
	@printf "================================================================================\n"
	@printf "                               Start to generate PNG file\n"
	@printf "================================================================================\n"
	@$(MAKE) $(patsubst $(SRC)/%.plantuml,$(OUTPUT)/%.$@,$(shell ls -1t $(SRC_FILES)))

$(OUTPUT)/%.png: $(SRC)/%.plantuml
	plantuml -charset UTF-8 -tpng -stdrpt:1 -recursive $< -o $(OUTPUT)

$(DEPEND_PLANTUML): $(SRC_FILES)
	@mkdir -p $(BUILD_FOLDER)
	@find_includes() { \
		sed \
			-e "s,^[[:space:]]*!include \([^<].*[^>]\)$$,$${1}/\1," \
			-e t -e d "$$2" \
			| paste -sd " " -; \
	}; \
	printf "# GENERATED BY make depend\n" > $@; \
	printf "# DO NOT EDIT\n\n" >> $@; \
	for file in $^; do \
		name="$$(basename -s .plantuml "$$file")"; \
		includes="$$(find_includes "$(SRC_PLANTUML)" "$$file")"; \
		printf "$(OUTPUT)/%s.eps: %s\n" "$$name" "$$includes"; \
	done >> $@

latex:
	@printf "================================================================================\n"
	@printf "                               Start to generate PDF file\n"
	@printf "================================================================================\n"
	@latexmk

clean_eps:
	@rm -rf $(OUTPUT_PLANTUML)/**/*.eps $(OUTPUT_PLANTUML)/*.eps
	@rm -f $(DEPEND_PLANTUML)

clean_latex:
	@latexmk -c

clean_vscode:
	@rm -f *.toc *.out *.log *.lof *.ist *.glo *.fls *.fdb_latexmk *.aux *.acn *.synctex.gz *.pyg
	@rm -f *.lol *.bcf *.xml *.acr *.alg *.bbl *.glg *.blg *.gls

clean: clean_eps clean_latex clean_vscode

.PHONY: all clean eps clean_eps latex clean_latex

-include $(DEPEND_PLANTUML)
