name: LaTex CI

on:
  push:
    tags:
      - "*"
    branches:
      - "master"
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_run:
    workflows: ["Docker Build"]
    types:
      - completed
  push:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/thorkel-dev/latex/alpine-texlive:latest
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      # Checkout the branch.
      - name: checkout repo
        uses: actions/checkout@v2

      - name: build pdf
        run: make all

      - name: Build schemas
        run: make png

      # Create an artifact that contains the output folder
      - name: Archive PDF and schemas
        uses: actions/upload-artifact@v3 # https://github.com/actions/upload-artifact
        if: ${{ success() }}
        with:
          name: output
          path: |
            bin/*.pdf
            schemas/**/*.png
          retention-days: 14

      - name: Archive log
        uses: actions/upload-artifact@v3 # https://github.com/actions/upload-artifact
        if: ${{ failure() }}
        with:
          name: output
          path: |
            .temp/*.pdf
            .temp/*.log
          retention-days: 14

      # Create a release that contains the generated PDF, named according to the name of the tag
      # The release is created only if the trigger is a pushed tag
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/') # it's a pushed tag
        uses: svenstaro/upload-release-action@v2 # https://github.com/svenstaro/upload-release-action
        with:
          repo_token: ${{ secrets.github_token }}
          file: bin/*.pdf
          file_glob: true
          tag: ${{ github.ref }}
