name: Makefile CI

on:
  push:
    branches: [ "master" ]
    tags:
      - "*"
  pull_request:
    branches: [ "master" ]
    types:
      - opened


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build pdf
      working-directory: ./ebauches
      use: todo
      run: make all
